### PR TITLE
feat: add confirm btn to upload post

### PR DESCRIPTION
**Pull request by Thaumy**
- 将"保存博文"字样修改为"上传博文", 并修改相关代码命名
- 为上传博文添加了确认提示

### CODE REVIEW

**Comment by cnblogs-dudu** [comment]
保存博文时报错：
```
Error running command vscode-cnb.save-post: command 'vscode-cnb.save-post' not found. This is likely caused by the extension that contributes vscode-cnb.save-post.
```

**Comment by cnblogs-dudu** [comment]
[package.json#L152](https://github.com/cnblogs/vscode-cnb/blob/v1.8.6/package.json#L152) 改为上传博文

**Comment by Thaumy** [comment]
Fixed

**Comment by laggage** [comment]
> 为上传博文添加了确认提示

May be its better to have an option for this, just my opinion :)

**Comment by cnblogs-dudu** [comment]
@laggage this icon and the right one are too small and easy to misclick.

**Comment by Thaumy** [comment]
Maybe it's better to leave a setting option for this feature

**Comment by cnblogs-dudu** [comment]
@Thaumy add an option to disable Push confirmation dialog.

**Pull request merged**
